### ISSUE TITLE
Add "Post-It" to .desktop keywords

### ISSUE THREAD

**Issue by acerspyro** [vixalien/sticky#105]
I presume it would be considered "fair use" (if they even notice at all) to add this brand name to the `Keywords` entry of sticky's .desktop file, especially since it's a generic trademark, like Scotch Tape, Dumpster, Kleenex, Band-Aid, etc.

I often end up searching for "Post-It" instead of "Sticky Notes" in my overview because corporate advertising got to me, and I'm sure I'm not alone.

I do believe sticky notes pulls up on Windows if you search for Post-It.

**Comment by vixalien** [comment]
This is a nice suggestion, and PRs are welcome.

You can simply add the term to the desktop file

https://github.com/vixalien/sticky/blob/4b0dfc49cf8b0200f9ab45b0b11c626baeb85ff2/data/com.vixalien.sticky.desktop.in.in#L11

I would, however, recommend searching or testing if hyphens are allowed in desktop files.

Thanks;

**Comment by acerspyro** [comment]
Thank you, PR opened.
