### ISSUE TITLE
Feature request: Save note window sizes and positions

### ISSUE THREAD

**Issue by TriVoxel** [vixalien/sticky#112]
I ran into a situation today where I opened Sticky Notes and had a bunch of really tiny (default size) note windows open, all centered on my monitor. It was kind of annoying, and reminded my that a multi-window app suck as Sticky Notes doesn't work well on Wayland. However, there are several drafts for the Wayland protocol to allow applications to re-organize and resize windows relative to the main window. I'd really appreciate if you would join these Wayland design discussions, as Sticky Notes is an app which would really benefit from saving window dimensions and positions. This way, users could fully quit the app, pull it up later, and have all their notes sitting just the way they left them. That would be nice, and the developers really need input from app developers like you to make a viable protocol like this,

~~At the very least, could you please store the last window dimension for the notes? That way, users can open the note up and not need to resize it every time. Thanks!~~ (seems this is already done, just doesn't work 100% of the time?)

**Comment by PHHENS** [comment]
+1 Most needed feature here : persistent Window Sizes and Positions.

**Comment by PHHENS** [comment]
Dear Developer,
I found Sticky Notes is a great app, thank you for your work on it.
This app would be totally perfect if it could preserve notes sizes and positions after restarting session.
Thanks for understanding this need

**Comment by nibexo** [comment]
+1

**Comment by vixalien** [comment]
> I'd really appreciate if you would join these Wayland design discussions, as Sticky Notes is an app which would really benefit from saving window dimensions and positions.

I would like to know where those discussions are being held.

Sticky Notes already saves and restores the sizes of windows, and we can't do the same for the position since it's a wayland limitation.
