### ISSUE TITLE
Dark-colored notes?

### ISSUE THREAD

**Issue by joaocandre** [vixalien/sticky#123]
I've just installed Sticky Notes and the color for each note seems a bit too dark, a darker shade than the screenshots on the project page:

![Screenshot from 2024-05-03 01-00-11](https://github.com/vixalien/sticky/assets/1812344/f44a74a4-9467-4bf0-b61e-e8fa48fef346)

Is this by design or caused by some bug? I'm running Archlinux with Gnome (v.46).

Any way to edit background and text color on each note?

**Comment by vixalien** [comment]
Yes, that's correct behaviour

**Comment by joaocandre** [comment]
Fair enough, it just different than the images on the README.

For what is worth, I do believe that shade is a bit too dark, kind of decreases readability. It would be cool if one could modify the default colors.
