### ISSUE TITLE
Feature request: add a 'New Note' entry to Desktop's context menu

### ISSUE THREAD

**Issue by joaocandre** [vixalien/sticky#126]
Gnome Shell's Desktop's context menu is, in my opinion, entirely redundant, and adding a  'New Note' option would add some practical utility to it.

Alternatively, a Gnome Shell extension that placed the '+' button on the panel would also be useful.

**Comment by vixalien** [comment]
Pull requests are appreciated !!

I believe one just need to edit the desktop file since you can already
launch `com.vixalien.sticky -n` to launch a new note.

**Comment by joaocandre** [comment]
I have little to no experience in Gnome development, but I can look into it once I find the time.

(likely will start by reverse engineering some simple extension to implement this)

**Comment by joaocandre** [comment]
>  `com.vixalien.sticky -n` to launch a new note.

after testing, that doesn't seem to work, I only get:

    Gjs-Console-Message: 02:44:23.000: Storing Notes at: ~/.local/share/com.vixalien.sticky/notes


the same goes for `com.vixalien.sticky -i`.

**Comment by vixalien** [comment]
> I do get a notification of 'Sticky Notes is ready' though.

You probably already have Sticky Notes running.

**Comment by joaocandre** [comment]
Indeed it does seem the case, but I wasn't sure if that was the planned behavior or a bug; I was able to override the desktop context menu through a simple Gnome Shell extension, but, as it stands, needs to close all open notes before creating a new one, and as a result the open/closed status of each note is lost:
![Screenshot from 2024-06-03 01-47-04](https://github.com/vixalien/sticky/assets/1812344/72c24de8-0447-4b6f-8e80-b73da18113da)

Nevertheless, adding a new note through the '+' button and through the CLI leads to two very different outcomes, which I think can be improved upon.

In any case, I may submit a PR with it or just extend the extension with additional features, such as nautilus integration and a panel indicator.

**Comment by joaocandre** [comment]
I submitted a PR to update the desktop file of the app to add the 'New Note' action, but that only updates the extra options on the app launcher (e.g. secondary click on the dash); seems to me that the general/main background context menu is very much WM-dependent, so it's perhaps best to approach this on a case-by-case basis, even this is a GTK app and thus the Gnome ecosystem can be assumed.

In any case, I wrote a simple [Gnome extension](https://github.com/joaocandre/sticky-notes-integration) that implements this option in the background menu (and moves the note to the cursor position), in addition to other features like a general purpose panel indicator.
An extension ends up being simpler to write (no need to delve into the app's extensive code base) and easier to debug.

I haven't thoroughly tested it, but it works well enough at the moment.
Naturally you're welcome to review it!

**Comment by vixalien** [comment]
> the general/main background context menu

what does this mean?

**Comment by joaocandre** [comment]
the context menu you get when you right click on the desktop background; GJS calls it a [background menu](https://github.com/GNOME/gnome-shell/blob/0cdddaa4a7fcb5a92b011da94e1ad66129e3c81d/js/ui/backgroundMenu.js).

**Comment by vixalien** [comment]
this thing?

![image](https://github.com/vixalien/sticky/assets/37999241/802fdc66-fc81-4bec-bc6f-bd5126ea83b9)

**Comment by joaocandre** [comment]
Yes, that extension updates it to [this](https://raw.githubusercontent.com/joaocandre/sticky-notes-integration/main/resources/background_menu.png).

**Comment by vixalien** [comment]
I don't think there's a way to add a menu option to GNOME Shell's desktop popover, without using an extension like you're currently doing

**Comment by DodoLeDev** [comment]
> I don't think there's a way to add a menu option to GNOME Shell's desktop popover, without using an extension like you're currently doing

@vixalien

While it's not possible, you could however link to the developed extension in order to allow the user to install it (or even more, install it with in one click thanks to [the following D-Bus call](https://stackoverflow.com/a/73044893)).

¯\\\_(ツ)\_/¯
