### ISSUE TITLE
Update current note in All Notes Window as the user types in it

### ISSUE THREAD

**Issue by amethystgosling** [vixalien/sticky#136]
Following GNOME HIG and to show changes are saving.

**Comment by vixalien** [comment]
This is what happens currently. no?

**Comment by futomaki-bit** [comment]
[Screencast from 2024-09-15 23-35-21.webm](https://github.com/user-attachments/assets/0dbfc666-59e6-4457-89b7-fe1ae07930a9)

It works for me :)
