### ISSUE TITLE
Polish: add "All Notes" and "New Note" button in app shortcut context menu

### ISSUE THREAD

**Issue by amethystgosling163** [vixalien/sticky#138]

**Comment by vixalien** [comment]
"New Note" already exists. It's just that I haven't made a new release yet.

If someone is interested on working on this, here are the steps:

First, you need to add a command line option, and handle it. you just need to add an `all-notes` option that will open all notes, and handle it as `new-note` is already present.

https://github.com/vixalien/sticky/blob/9a22dc859e0e245da5532e8aea5bb5fb55afbcfd/src/application.ts#L93-L147

Then you add a new desktop action here.

https://github.com/vixalien/sticky/blob/main/data/com.vixalien.sticky.desktop.in.in
