### ISSUE TITLE
Feature Request: Move to system tray?

### ISSUE THREAD

**Issue by ariahrism** [vixalien/sticky#141]
I'm currently using KDEneon Plasma v6, and notes app works great! Thank you!

But it takes space in the task manager, and clutters the workspace. 

If it lived in the system tray (like dropbox) I'd leave it running all the time. As it is, I usually close the app to get it out of my way.

Thanks in advance

**Comment by vixalien** [comment]
Since this is a GNOME app, it's usually thought that you move apps you don't want to see to an unused workspace.

Why do you want the app to be running the background anyway?

**Comment by ariahrism** [comment]
As these are "sticky notes" , I like the option of having one or two always on top of other windows, like sticky notes IRL. (That or stickied to the desktop, but that's another topic)

So I want one always on top, but I don't want it to take space in the taskbar.

For any other applications, yes I move them to other work spaces. But this app has a special use case.

**Comment by vixalien** [comment]
> So I want one always on top, but I don't want it to take space in the taskbar.

AFAIK, when you open an app from the systray (which doesn't exist on GNOME) it will add an entry to the taskbar (which doesn't exist on GNOME either), so I'm unsure how this would work anyway.

The modern replacement to the systray is called Background Apps, and Sticky Notes is NOT meant to be run in the background, at all.

![image](https://github.com/user-attachments/assets/f344df50-4327-4e08-ab33-c805959b771a)

> That or stickied to the desktop

You can do this on GNOME by right clicking on the headerbar.

![image](https://github.com/user-attachments/assets/7949ad86-5143-48eb-b2d5-80e7f73d375c)

**Comment by ariahrism** [comment]
Yeah my system has the always on top function, just trying to remove the taskbar entry.

**Comment by vixalien** [comment]
> just trying to remove the taskbar entry

This is not supported
