### ISSUE TITLE
[Feature suggestion] Sync with google keep?

### ISSUE THREAD

**Issue by ludvigng** [vixalien/sticky#16]
Hello!

I'm curious if it would be possible to make this app sync with google keep? Keep is what I usually use on my phone for a lot of my notes, and having this app be able to sync with my computer would be a very welcome addition.

However, I don't know how hard it'd be. I haven't found any app so far with the ability, so I suspect it's not easy. There is an API document available here: https://developers.google.com/keep/api/reference/rest for retrieving and sending notes it seems, but I have no idea if it works in practice.

I'm also not sure how feasible it is, since keep also allows notes to have pictures attached, and checkboxes, and these might be out of scope for the project. But I figure it's something worth asking either way. :)

**Comment by vixalien** [comment]
I think this would be better implemented by a third party not in the notes
app itself

**Comment by ludvigng** [comment]
Yeah that's reasonable, but I was thinking if it was possible to use the already existing gnome-online-accounts for this, since it already handles the login and stuff for the google account? But maybe it'd still be better as a separate service.

**Comment by ludvigng** [comment]
Hm, yeah I think it might not support keep right now. I'm going to ask on their gitlab if it's feasible to use as a backend, or if it's possible to add to it, because it might be something useful to other note-taking apps in the gnome ecosystem.

**Comment by vixalien** [comment]
I'm closing this in favor of #51
