### ISSUE TITLE
Tray option

### ISSUE THREAD

**Issue by RasheedAZ** [vixalien/sticky#18]
Hi Angelo. Thank you to this beautiful and useful app which I didn't of know of any alternative at all for the Linux desktop.

I wanted to ask: how about if the app stays in the tray when the main window is closed and only the sticky notes are on the desktop?

That way, the icon will not take up space in the dock when the main window has been closed.

**Comment by vixalien** [comment]
hmm this is really not considered because the "tray" is not officially supported by GNOME and is hence not a paradigm I want to support as well.

I'm pretty sure one could make an extension that does this tho...

**Comment by DodoLeDev** [comment]
Instead of moving the window to "tray", you can now use the [Background Apps](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2624) feature to hide the main window while still notifying the user it's still running in background

**Comment by vixalien** [comment]
I don't see why the app would run in the background though? It doesn't provide any actions in the background.

The feature is more useful, say for music players and the like.

**Comment by DodoLeDev** [comment]
> I don't see why the app would run in the background though? It doesn't provide any actions in the background.
> 
> The feature is more useful, say for music players and the like.

I think the initial idea was to display the notes without an icon in the taskbar, while still clearly indicating to the user that the app is still running

**Comment by vixalien** [comment]
> to display the notes without an icon in the taskbar

I have trouble imagining why this would be needed ;(

Sticky Notes is still just an application, and not displaying it in the dash seems weird and might confuse some users. what do you think ?
