### ISSUE TITLE
I've been had sometrouble, can the developers help me?

### ISSUE THREAD

**Issue by alef-coder** [vixalien/sticky#24]
Hello, I loved the app, but I've been had some problems that it will be listed:
- The icons don't work properly
- The autosave or the actual save isn't working too, the note disappears after close.
- The main icon of menu 

![Captura de tela de 2023-03-06 11-06-29](https://user-images.githubusercontent.com/72264836/223149678-881a193b-4ad2-4ddb-88d0-0d4927b0ba25.png)

![Captura de tela de 2023-03-06 11-08-00](https://user-images.githubusercontent.com/72264836/223149687-61d63029-b7f6-42f5-b89f-1bc7dc5b593a.png)

**Comment by alef-coder** [comment]
![Captura de tela de 2023-03-06 11-12-21](https://user-images.githubusercontent.com/72264836/223153406-2f4d80b5-4a5d-470b-b646-3816bbfababa.png)

**Comment by alef-coder** [comment]
By the way, this is the best UI DESIGN in the market of Linux. Really, it is beautiful and works so smoothly. 
You have a big potential in your hands. wish you luck.

**Comment by alef-coder** [comment]
I use Ubuntu 22.04 and, yes, I made by flathub, and It's updated.
And today I've found another issue:
- when a note is full of words, the app starts to slow down.
- when I need to copy/paste from the app, stops working. (especially after I made a lot of notes)
 also, asks me to close down. After rebooting, I lost the last saved notes.

* The last issue of autosave despaired after the update

P.S: I really loved the app, even with some issues, I'm still using because the UI it's impressively well done. 
I would like to recommend more colors ;)

**Comment by vixalien** [comment]
about the colors, I'm not really sure what's the issue. for a quick diagnosis, try installing [Icon Library]() and search for the icons (`format-text-bold-symbolic` and `com.vixalien.sticky`) and see if they are there. if the `bold` icon is not present, it may be because the yaru theme used by ubuntu do not provide those icons.

have you done some modifications to your system?

as I said before, I'm not really sure why this happens...

**Comment by devaniljr** [comment]
I'm completely smitten with this app. It outperforms the Windows equivalent. I'm experiencing the same issue with not saving the notes. All notes vanish after I close the window. Ubuntu 22.04.02 and last version. Hoping for a fix.

**Comment by vixalien** [comment]
it's gonna get fixed in the next release. hopefully I'll get it published tonite.

**Comment by alef-coder** [comment]
After this last update, everything has been solved. Except the fact when the note is fulfilled of content the program slowdown and copy/paste thing still stops everything

**Comment by vixalien** [comment]
sorry for reaching out late, I completely missed your message. I'm happy to report I'll be investigating the slowdowns and will update accordingly
