### ISSUE TITLE
Apply for GNOME Circle

### ISSUE THREAD

**Issue by automerisnaranja** [vixalien/sticky#33]
It would be very great to have this app in [GNOME Circle](https://circle.gnome.org/).

**Comment by vixalien** [comment]
Hey thanks! I'm considering this and thanks for you being helpful in the app, but first of all I need to make this app "reliable"

**Comment by vixalien** [comment]
I've [applied](https://gitlab.gnome.org/Teams/Circle/-/issues/166) for GNOME Circle now.

let's wait for a review
