### ISSUE TITLE
Editing a note isn't intuitive

### ISSUE THREAD

**Issue by automerisnaranja** [vixalien/sticky#34]
## Affected version
0.1.1

## Description
Editing a note requires a double click, but this isn't intuitive or mentioned explicitly in the UI. I think an edit button (icon-only) would be better.

**Comment by vixalien** [comment]
would it be better if it only required one click? but what about the misclicks...

to be honest the point about sticky notes is to be able to edit them easily so I think the current way is half as good

**Comment by vixalien** [comment]
thanks. I'll work on this soon...

**Comment by vixalien** [comment]
Sticky now doesnt require a double click to open a note
