### ISSUE TITLE
Potential integration with Nextcloud Notes folder?

### ISSUE THREAD

**Issue by githubtefo** [vixalien/sticky#4]
Hi! The App looks amazing!
I was wondering if there would be a simple way to integrate the Notes that exist as .txt files in a folder with the ones from the App.
This would allow a flawless interaction with Nextcloud Notes.
Thanks!

**Comment by vixalien** [comment]
hmm I'm not sure how to do that... do you have any pointers?

**Comment by githubtefo** [comment]
For instance, is there a dir where individual notes are stored are single flies? If that's the case, it would be as simple as assigning that dir as the Nexcloud Notes one.

**Comment by vixalien** [comment]
yes. we are planning to change how notes are stored by storing them in
their own files. once that's done, I'll update this issue.

**Comment by githubtefo** [comment]
Thank YOU! That will be super useful for synchronization, not only with Nextcloud I guess.

**Comment by githubtefo** [comment]
Any updates on this regard @vixalien? Thanks!
