### ISSUE TITLE
Strange behaviour with bold, italic, underline and strikethrough

### ISSUE THREAD

**Issue by Nokse22** [vixalien/sticky#42]
Sometimes a note doesn't save the fact that a text is bold italic strikethrough or underlined. If it saves and you remove it it doesn't save the fact that you removed it.

[Screencast from 2023-03-22 12-06-08.webm](https://user-images.githubusercontent.com/44558032/226887143-c585826b-430b-4b95-97a4-41c4781612bf.webm)

**Comment by vixalien** [comment]
seems the tag change events are not being propagated correctly. I'll investigate.

does it work when you add a word after adding the tag (bold, italic etc. are called tags in sticky)

anywho I'll investigate when I get to PC soon (probably)

**Comment by vixalien** [comment]
confirmed this. working on it as we speak!
