### ISSUE TITLE
Formatting buttons not showing

### ISSUE THREAD

**Issue by hpicelli** [vixalien/sticky#74]
The font formatting is showing only a "!" icon.
Pop_OS 22.04
Sticky Notes 0.2.0 (Flatpak)
Tested installation on 2 systems.
![Screenshot from 2023-06-13 17-48-06](https://github.com/vixalien/sticky/assets/3333923/0dbc3c8f-c1ab-4b40-bcb0-e165305eef15)

**Comment by vixalien** [comment]
please install the flatpak from this action https://github.com/vixalien/sticky/actions/runs/5331867608/ under artifacts.

Install the flatpak and then report back if the issue is fixed

**Comment by hpicelli** [comment]
Hi Angelo,
Installed the flatpak that you work and it's ok!
Best regards,
Henrique
[image: image.png]

**Comment by hpicelli** [comment]
Hi,
The issue was fixed.
Thank you!
![image](https://github.com/vixalien/sticky/assets/3333923/0829017b-7426-49b5-a999-5877477957b5)
