### ISSUE TITLE
it does not open

### ISSUE THREAD

**Issue by trytolearn51** [vixalien/sticky#77]
Hello

Thanks for your great project .

i really don't know why it stops working for me since last days.

How can i see the logs or anything useful to solve this problem

**Comment by trytolearn51** [comment]
flatpak run com.vixalien.sticky
Gjs-Console-Message: 09:51:07.264: Storing Notes at: /home/david/.var/app/com.vixalien.sticky/data/com.vixalien.sticky/notes

(com.vixalien.sticky:2): Gdk-ERROR **: 09:51:08.362: The program 'com.vixalien.sticky' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 407 error_code 167 request_code 152 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by vixalien** [comment]
Did you try clearing all data, then reinstalling?

**Comment by trytolearn51** [comment]
how should i chean all data ?

**Comment by vixalien** [comment]
usually the data will be at `~/.var/app/com.vixalien.sticky`. you can just `rm -rf` that.

note that all your notes will be lost though

**Comment by vixalien** [comment]
thank you. did it work?

**Comment by trytolearn51** [comment]
flatpak run com.vixalien.sticky
Gjs-Console-Message: 12:07:01.402: Storing Notes at: /root/.var/app/com.vixalien.sticky/data/com.vixalien.sticky/notes

(com.vixalien.sticky:2): Gtk-WARNING **: 12:07:01.770: Unable to acquire session bus: Error spawning command line “dbus-launch --autolaunch=94d91eaee67e4e468f9df857fafd05cf --binary-syntax --close-stderr”: Child process exited with code 1

(com.vixalien.sticky:2): Gdk-ERROR **: 12:07:01.942: The program 'com.vixalien.sticky' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 360 error_code 167 request_code 152 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Unfortunately not.  i try clearing data + reinstalling + installing multiple times,   have no idea why it doesn't work, it is great project by the way.

**Comment by vixalien** [comment]
this is extremely weird. does this happen for other flatpak apps too?

also I noticed you are running `flatpak run com.vixalien.sticky` as root. Could you try logging in as a normal account and try again?

**Comment by vixalien** [comment]
hey! any update on this?

**Comment by trytolearn51** [comment]
Hello !!

Yes it is working  :)

**Comment by berkaykrc** [comment]
I get this error on Fedora 42 KDE Wayland. Used flatpak to install the program. I have crash report.
