### ISSUE TITLE
[Feature suggestion] Checkboxes

### ISSUE THREAD

**Issue by vergelli** [vixalien/sticky#80]
Hello there, first of all, great job with this one, thank you for your effort.

It would be awesome to have Checkboxes, ideal for when you have a list of tasks, or #TODO's and you can check them while you are doing.

Best regards.

**Comment by evoke0** [comment]
Interesting feature, but is it really necessary? Sticky Notes already has markdown implemented, so you can format you text with just a couple clicks. You may mark completed tasks with ~strikethrough~.

**Comment by vixalien** [comment]
related to #2

well, this would be a nice feature, but it's not as trivial to implement in GTK as having checkboxes inside a textview which can handle all the edge cases would be hard. I can't see myself working on this really as I don't even know how to.
