### ISSUE TITLE
[Feature Request] Minimalist view

### ISSUE THREAD

**Issue by janjitsu** [vixalien/sticky#83]
I would like to keep the sticky notes on a very small window, and together with the feature of changing the font size #17, this minized view would remove the buttons and spacing for the headers, with only a arrow to move it around and unminimize-it, I don't know the stack for developing gtk+3 apps but I'm a developer and I can help!

**Comment by vixalien** [comment]
This is a GTK4 application (not GTK3) but they are pretty similar anyways. do you have an idea of how the design of minimal mode would look like?

**Comment by vixalien** [comment]
I believe the current views are already minimal. Please feel free to add more details if necessary
