### ISSUE TITLE
Streamline the usage of `Ctrl+W`

### ISSUE THREAD

**Issue by maymage** [vixalien/sticky#85]
Hi all, 

I was trying out Sticky Notes today for the first time: great little app for taking notes on the fly!

It seems suboptimal, that when taking a note, then `Ctrl+W` is showing a `Discard|Cance|Save` type dialog, instead of just saving the note and closing that window.

I think the workflow would be better, if 

* for the note taking window `Ctrl+W` would just save the notes and close the window without any confirmation, while `Ctrl+Q` should be ineffective. In this way we save a click event and the rist of losing data is diminuished. 
* for the main window  `Ctrl+Q` (and `Ctrl+W` perhaps too, if not ineffective) should ask for a confirmation dialog, kind of `|Discard Open Notes and Quit|Cancel|Save Open Notes and Quit|`

**Comment by vixalien** [comment]
Oh sorry. In the keyboard shortcuts. `Ctrl+W` is said to delete a note. and as such is a destructive action, a confirmation is asked first. would you rather it just closes the note window?

**Comment by maymage** [comment]
thx
