### ISSUE TITLE
Incorrect menu tooltips

### ISSUE THREAD

**Issue by rene-coty** [vixalien/sticky#87]
The menu tooltips of the 'all notes' window and the notes windows will always display "main menu"
See screenshots below (here in French): all the tooltips are "_menu principal_" (=main menu) when it should instead display the hovered menu option ('Keyboard shortcuts', 'Quit', 'All notes window'...)
![Capture d’écran du 2023-08-18 11-33-13](https://github.com/vixalien/sticky/assets/95506494/9fc08c9e-bee8-428a-a360-a014b9e49935)
![Capture d’écran du 2023-08-18 11-33-24](https://github.com/vixalien/sticky/assets/95506494/80031bc7-e502-490a-9cb7-461d3a540a6b)
![Capture d’écran du 2023-08-18 11-33-37](https://github.com/vixalien/sticky/assets/95506494/5de5d434-6dba-42cb-9651-f5d383728739)

PS: this doesn't seem to be caused by the translation, it is the same tooltip that has been applied to all the menu options

**Comment by vixalien** [comment]
I don't know what's happening. because in the original/untranslated English version, I can still see the correct notes.

![image](https://github.com/vixalien/sticky/assets/37999241/deba97bc-2679-4ce2-a4dd-3f8bd818cf8d)

Did this issue happen after yesterday's update?

**Comment by rene-coty** [comment]
The colour switches were OK, but not the text buttons... I'll check the version but to me it seemed that it was related to the latest releaseLe 18 août 2023 13:04, Angelo Verlain Shema ***@***.***> a écrit :
I don't know what's happening. because in the original/untranslated English version, I can still see the correct notes.

Did this issue happen after yesterday's update?

**Comment by vixalien** [comment]
okay this is bizarre because you aren't supposed to see tooltips of those menu items

**Comment by vixalien** [comment]
seems to be fixed on latest build
