### ISSUE TITLE
Colors aren't correct

### ISSUE THREAD

**Issue by Ptaski** [vixalien/sticky#91]
Colors do not match with ones in example:
![image](https://github.com/vixalien/sticky/assets/132298731/1a94b7e1-bd51-478d-a473-1bd133622b35)
Colors are darker.

Uname -a output:
`Linux lenovo 6.4.6-76060406-generic #202307241739~1692717645~22.04~5597803 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux`
Pop_OS! - I'm will provide more information if needed.

Is this a bug?
Many thanks for this project ❤️

**Comment by lisasnt** [comment]
If you use Dark Style, the sticky notes colors change too
