### ISSUE TITLE
add a copy button

### ISSUE THREAD

**Issue by sigmaSd** [vixalien/sticky#99]
I find myself using sticky to copy stuff,  so maybe its a good addition

![image](https://github.com/vixalien/sticky/assets/22427111/3f89ac13-d7d1-494b-9143-8f51e9fb8877)

**Comment by vixalien** [comment]
I want to know: How often do you copy a note's text?

**Comment by sigmaSd** [comment]
I just started using this app, so for now this is what I use it for (copy pasting some plain text passwords)

Its very possible that's its not a typical use case

**Comment by vixalien** [comment]
That's what I'm thinking, too. Can't you just select the text and copy it?

**Comment by sigmaSd** [comment]
If I try to copy from the initial menu it doesn't work 
![image](https://github.com/vixalien/sticky/assets/22427111/c847d915-bdb1-42bf-8cbd-427be5787b29)

I have to open the note then copy

**Comment by vixalien** [comment]
yes. is there a problem with that?
